### ISSUE TITLE
Tag docker images

### ISSUE THREAD

**Issue by runraid** [dperson/nginx#10]
If possible, it would be great to tag pushed images with a build number and keep a few of them around.  Right now I only see "latest". If a breaking change is pushed out and we update, there's no easy way to rollback.

https://hub.docker.com/r/dperson/nginx/tags/

**Comment by dperson** [comment]
@runraid I'll try to come up with a tag naming scheme for previous versions. I'll also try to get the 'disable IPv6' option done for you today.
