### ISSUE TITLE
Stream are not working

### ISSUE THREAD

**Issue by anthonyraymond** [dperson/nginx#13]
There are missing some lines in `/etc/nginx/nginx.conf` for stream to be working :

```
stream {
        include /etc/nginx/conf.d/*.stream;
}
```
This will be the minimum required to enable streams, i don't know if anything else is required or not. But with this it does work.

Without these lines, all `/etc/nginx/conf.d/*.stream` files are being ignored.
As a test you can write a random string in `/etc/nginx/conf.d/default.stream` and run `service nginx configtest` from inside the container, it will result in a config being OK. It means the file is being ignored.

**Comment by dperson** [comment]
Thank you for the report, I had added it but not used / tested it, sigh. I've got a new version I just pushed with the following diff \**facepalm*\*.

```
      echo "\n\nstream {\n    include /etc/nginx/conf.d/*.stream;\n}" \
-                 /etc/nginx/nginx.conf && \
+                 >>/etc/nginx/nginx.conf && \
```

**Comment by anthonyraymond** [comment]
Alright ^^ close enough.

Thanks for the fix.
