### ISSUE TITLE
index.PHP

### ISSUE THREAD

**Issue by smathev** [dperson/nginx#15]
Hi.

Thanks for an awesome container, I've been using it alongside your vpn-container and everything is working smoothly with the necessary redirects to other containers.

However, I also want Nginx to host an index.php site to get some information. Specifically I wanted to run https://www.ezservermonitor.com/esm-web/documentation, but I'm unable to set it up.

For reference this is the docker run command I'm currently using:
"
docker run -it --name web2 -p 80:80 -p 443:443 -e SSI=y \
--link vpn:deluge --link vpn:sonarr --link vpn:radarr -d \
-v /home/core/.docker/configs/nginx:/etc/nginx/ \
-v /home/core/.docker/configs/nginx/www:/srv/www:ro \
dperson/nginx 
"

Redirects and all else seems to be working - but I can't for the life of me setup PHP to work. I'm pretty sure it's cause there isn't a PHP-engine in the current nginx-container, but I'm also unable to apt-get it when I enter the container. 

Do you have any suggestions how I might set this up?

Thanks in advance.

PS. I recognize this isn't directly related to your container, per se, but I noticed that you're very helpful in general and I'm hoping you might help me resolve this issue :)

**Comment by dperson** [comment]
Unlike most web servers nginx doesn't support running PHP/Python/Perl/etc as a sub-process to execute the content it's serving. You'll have to proxy to another container that will execute it.
