### ISSUE TITLE
ruTorrent/deluge webui not working properly with nginx proxy/OpenVPN

### ISSUE THREAD

**Issue by jonatronnn** [dperson/nginx#18]
I've set up rutorrent/nginx/openvpn as per the instructions but when I go to the url for rutorrent it loads the page incorrectly as you can see in the image.
![1](https://user-images.githubusercontent.com/38166227/38459741-a4fce0a4-3aa5-11e8-88cd-5b6ba6898a9a.jpg)

I'm really struggling to figure out what I need to do to get this working correctly.

If I start ruTorrent without passing through openvpn/nginx I can navigate successfully to the page.

I have a similar issue when using Deluge in the same way whereby the page seems to load and has the correct header, but the page shows blank.

Could be a similar issue? Please let me know what information you need from me in order to diagnose the issue.

As a side note, I'm using a few of your docker setups and the documentation and support you provide for them seems fantastic and I really appreciate any help you can give me.

**Comment by jonatronnn** [comment]
I was able to get the Deluge webui working! was missing a trailing / however I've been looking through some posts regarding getting the daemon working but the information is unclear and outdated, do I simply need to expose the correct port on my VPN container or do I still need to set up a tcp proxy?

My issue with rTorrent still exists.

**Comment by dperson** [comment]
If you'll only want access on the local network you can set the `-r` option for `dperson/openvpn-client` and port forward to the openvpn container and skip the proxy entirely.

I don't really use deluge or rTorrent, I'm glad you (and others) have had success with deluge, I'm not sure where the issue you're seeing with rTorrent is coming from (first report that I know of).

Can you provide more details, IE the exact command line you're starting nginx with, logs from it and the rTorrent container?

**Comment by jonatronnn** [comment]
I am happy to only access these services via my local network so I have removed the nginx element and am now forwarding ports from the OpenVPN container.

I am able to access my Deluge Webui on port 8112 and sabnzbd on 8080 I am also able to access the rTorrent webui successfully using this method so that issue is resolved.

My only remaining issue is being able to access the Deluge daemon via the thin client on port 58846, I'll mess around with settings some more, but I can't think of why the webui would work and not this?

Is there any way for me to be certain that any internet traffic these containers use is only ever routed via the VPN?

**Comment by dperson** [comment]
Is the client port UDP? you'd have to specify that when setting up the port...

If you're using the network stack from the openvpn container, you can also specify the `-f` (firewall) option, it will block all non-VPN / non-DNS traffic from the container. To verify, if you have curl (or wget) in your container you can run `curl icanhazip.com` to return the address your request came from.
