### ISSUE TITLE
Can't get Deluge working

### ISSUE THREAD

**Issue by SolidRhino** [dperson/nginx#2]
Is there a way to proxy Deluge with this docker file? I must set a header with the following value:
proxy_set_header  X-Deluge-Base "/deluge/";

Now I type in this line, and can't get Deluge to work:
-w "http://deluge:8112;/deluge"

Nginx gives me the following error:
No Such Resource

No such child resource.

**Comment by dperson** [comment]
I've just added a way to add an extra header to web proxies. The `-w` flag now accepts an optional third field for headers (IE `-w 'http://deluge:8112;/deluge;X-Deluge-Base \"/deluge/\"'` for your use case). I don't use deluge, so can't say that it will work, but it's setting the requested values in the configuration file.
