### ISSUE TITLE
Handling URL Rewrites

### ISSUE THREAD

**Issue by louislang** [dperson/nginx#21]
I'm attempting to setup a reverse proxy for [linuxserver.io's sonarr](https://github.com/linuxserver/docker-sonarr) docker container. The docker container works fine, and I can successfully create both the nginx and Sonarr containers. The problem arises when I try and access the Sonarr container.

Specifically, instead of being presented the Sonarr web UI, I see the following:

`Sonarr Ver.`

If you inspect the page, you'll see valid HTML you'd expect from Sonarr. You can see several additional requests for CSS/JS, but these all fail with a 404. This appears to be caused by the fact that Sonarr expects these files to be served from `http://example.com/Content` however, I have Sonarr being served from `http://example.com/sonarr` behind nginx. This causes the requests to be routed to `http://example.com/sonarr/Content`.

Is there anyway to rewrite the URLs such that requests to `http://example.com/sonarr/Content/` are properly routed to the Sonarr container?

**Comment by jamitupya** [comment]
Any luck on this one? same issue as you currently.

**Comment by louislang** [comment]
@jamitupya I looked at it briefly a while ago, but haven't had much time to figure out a solution. I'll probably circle around to it when I have some more free time though. We might be able to create a rewrite on the nginx config, but I'm not sure if this container supports that directly or not.

**Comment by dperson** [comment]
A common issue is not having the trailing `/` on the URIs for both arguments to `-w`, IE:
```
-w "http://smokeping/smokeping/;/smokeping/"
```
and not:
```
-w "http://smokeping/smokeping;/smokeping"
```

**Comment by alackmann** [comment]
Note: for anyone else having this issue with Sonarr - you actually need to do some config in the app as well. 

In `/.config/NzbDrone/config.xml` you'll need to set a `UrlBase` value (eg. `sonarr`) and then the provided example templates should work correctly for the proxying. eg.

`-w "http://sonarr:8989/sonarr/;/sonarr/"`

(Remember trailing slashes are important here)
