### ISSUE TITLE
Docker-Compose Support

### ISSUE THREAD

**Issue by jamitupya** [dperson/nginx#22]
Trying to utilise your image via a docker compose file (in conjunction with your openvpn-client) however im trying to proxy multiple apps. i have tried every possible way to execute the "command: -w" command however just cant get it to work... and ideas?

command: "-w http://service1:80;/service1 -w http://service2:80;/service2"

**Comment by jamitupya** [comment]
figured it all out.

**Comment by gagandaroach** [comment]
Please do share your solution!

**Comment by jamitupya** [comment]
command: "-w http://service1:80;/service1" "-w http://service2:80;/service2" i think it was
