### ISSUE TITLE
Create arm build

### ISSUE THREAD

**Issue by giggio** [dperson/nginx#23]
Right now you only have a debian:stretch build, it would be nice to have arm ones to go with the open vpn client.

**Comment by dperson** [comment]
The ARM builds are based on alpine and the NGINX team doesn't provide builds for it or ARM for that matter.

**Comment by giggio** [comment]
I just ran on a Raspberry Pi 3 the [official nginx images](https://hub.docker.com/_/nginx/) available on Docker Hub, which includes ARM.

![image](https://user-images.githubusercontent.com/334958/47953412-12313480-df5c-11e8-857b-957f434d8395.png)

Both Alpine and Stretch (latest) ran just fine.

**Comment by dperson** [comment]
Those are built in a quite different manner, and I'd have to redo my container. I don't really have the time / interest to do that right now.

**Comment by frepke** [comment]
> Those are built in a quite different manner, and I'd have to redo my container. I don't really have the time / interest to do that right now.

Hello David,

I've the same question for my arm SBC. Do you know if there's an arm alternative for your nginx image?

kr.,
Frepke

**Comment by dperson** [comment]
You could add my `ENTRYPOINT` script to the official image most likely... but I don't really want to imitate them in building from source to create the image. If they make packages for ARM in their repos I'll be glad to create an image for it.
