### ISSUE TITLE
HTTP 400 Error on every post from the jackett UI when using reverse proxy

### ISSUE THREAD

**Issue by JRascagneres** [dperson/nginx#25]
I appear to be getting HTTP 400 Errors when issuing POST requests from a jackett UI when accessing through a reverse proxy whilst using openvpn for jackett. I've had a look around and seem to be hitting the issue described in a previous issue on the jackett repo: https://github.com/linuxserver/docker-jackett/issues/63#issuecomment-460004550

I don't understand the solution that was provided there. Can anyone help?

**Comment by d8ahazard** [comment]
Disable/remove

proxy_set_header Connection "upgrade"

If using something like NGINX Proxy Manager, disable websocket support...

**Comment by dperson** [comment]
I'm not sure what jackett is or why it won't support modern standards, but you're free to manually configure your reverse proxy to remove that setting.

**Comment by Charliedean** [comment]
Hi,

I have also come across this issue when something does not support the connection upgrade header.
I have tryed to overwrite the header when using the -w flag. 
Example:
-w "http://127.0.0.1:8223;/temp/;Connection \\"no\\" "

but in the default.conf inside the container, the custom header gets written first and then overwritten later by the hardcoded "## Required for websockets"

```
location /temp/ {
        proxy_pass       http://127.0.0.1:8223;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        # Mitigate httpoxy attack (see README for details)
        proxy_set_header Proxy "";

        proxy_set_header Connection no;


        ## Required for websockets
        proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_read_timeout 600s;

        ## Optional: Do not log, get it at the destination
        access_log off;
    }
```
Would writing the custom header after the "## Required for websockets" part fix this issue?
or is there another way of disabling headers? 

On another note, i don't think i was able to set the header to an empty string with \\"\\" as the container errored on startup
`invalid number of arguments in "proxy_set_header" directive in /etc/nginx/conf.d/default.conf:59`

Thanks

**Comment by dperson** [comment]
The headers don't *force* websockets to be enabled, they just allow support for them.

**Comment by Kallb123** [comment]
So is there actually a solution to this? It appears impossible to override the `proxy_set_header Connection` and `proxy_set_header Upgrade` headers because they are overwritten by the websocket code in the default.

Can you provide an example `-w` argument that would set these two headers for a proxy please?

**Comment by dperson** [comment]
There is now an override to disable use of websockets. If you add an additional argument to the `PROXY` environment variable or the `-w` command line argument, for example:
`"http://127.0.0.1:8223;/temp;;no"`

**NOTE**: There is already a custom header you can define as the third field, disabling sockets is the fourth field.
