### ISSUE TITLE
Container crashing

### ISSUE THREAD

**Issue by Nick1641** [dperson/nginx#26]
My nginx container is crashing. Attaching to the container reveals the following error codes:

> nginx     | /usr/bin/nginx.sh: eval: line 584: unexpected EOF while looking for matching `"'
> nginx     | /usr/bin/nginx.sh: eval: line 585: syntax error: unexpected end of file
> nginx     | 2019/07/08 14:18:09 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> nginx     | nginx: [emerg] cannot load certificate "/etc/nginx/ssl/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> nginx exited with code 1

I'm loading the container using docker-compose, config file [here](https://github.com/dperson/nginx/files/3368843/nginx.txt)

**Comment by jordanpotter** [comment]
I'm experiencing the same issue: https://github.com/dperson/nginx/commit/168005c50f7dec2136fb965e18ab660128860ad2#commitcomment-34213572

**Comment by dperson** [comment]
Yes, sorry about that. I didn't realize that the build hadn't finished when I did a docker pull ~45 minutes after the auto build should have kicked off. I didn't actually test the container that I just built *sigh*.

I've reverted the change, sorry for the problems.

**Comment by jordanpotter** [comment]
All good! Thanks for the quick turnaround! 

Btw if you wanted to create a separate Docker tag for Alpine, I'd be happy to be a beta tester 😄

**Comment by dperson** [comment]
@jordanpotter hey, I got around to working on alpine for the container once more. It's working for me now, there is an `alpine` tag that you can try out if you'd like.
