### ISSUE TITLE
nginx.sh script sed error on alpine image

### ISSUE THREAD

**Issue by jaycuse** [dperson/nginx#27]
After building the alpine image, I was having trouble getting a basic proxy running and would get this error
```
/usr/bin/nginx.sh: eval: line 584: unexpected EOF while looking for matching `"'
/usr/bin/nginx.sh: eval: line 585: syntax error: unexpected end of file
```
I managed to pinpoint the problem coming from the sed command while reading in the script options.
I was able to reproduce the problem sed command and fix it within the alpine image:
```
bash-5.0# echo "http://test:80/testing;/testing/" | sed 's/^\|$/"/g; s/;/" "/g'
"http://test:80/testing" "/testing/
bash-5.0# echo "http://test:80/testing;/testing/" | sed 's/^\|$/"/g; s/;/" "/g; s/$/"/g'
"http://test:80/testing" "/testing/"
```

I haven't fully tested this yet but it looks like the fix is to replace lines like:
` w) eval proxy $(sed 's/^\|$/"/g; s/;/" "/g' <<< $OPTARG) ;;`
to
` w) eval proxy $(sed 's/^\|$/"/g; s/;/" "/g; s/$/"/g' <<< $OPTARG) ;;`

**Comment by dperson** [comment]
The nginx container has been reverted from alpine for a while, but this could well be one of (if not *the*) reason it wasn't working. Thanks for the report, I'll give the migration another shot (with local builds) in the near future.
