### ISSUE TITLE
Help with Sonarr and Jackett communication through nginx

### ISSUE THREAD

**Issue by useful-devops-tools** [dperson/nginx#28]
I was wondering if you knew of any specific issues around running jackett behind this proxy, I'm using your vpn repo as well and have configured jackett and sonarr to use the vpn as there main internet connection and both can reach outside websites however they cannot talk to eachother.
Do you know what IP or URL I should be giving sonarr to allow it to talk to jackett?

Internet --- VPN Docker  --- Docker Containers sharing VPN connection (jackett & sonarr)

**Comment by dperson** [comment]
If they're using the network stack from my openvpn container, then they will both have the same IP address, and you can use `localhost` to talk to the other one.

**Comment by useful-devops-tools** [comment]
I tried using localhost but they were unable to communicate, would the reverse proxy settings of jackett be affecting it like the base prefix?

**Comment by dperson** [comment]
Could you share how you're starting the containers (either command-line or compose file, make sure to redact any private bits)?

**Comment by useful-devops-tools** [comment]
Sorry about the late reply and I appreciate the help! I just tried localhost with the 127.0.0.1 ip instead of 'localhost' and the ip and it worked!

Apologies for wasting your time but thanks for the help!

**Comment by dperson** [comment]
No worries. I'm really surprised that `localhost` doesn't work, but I'm glad you figured things out!
