### ISSUE TITLE
"SSL" conflicts with already declared size

### ISSUE THREAD

**Issue by wagaman** [dperson/nginx#30]
Hi, thanks for creating this docker image.

I ran the following line:
docker run -it --name web -p 81:80 -p 444:443 -p 51413:51413 -p 51413:51413/udp --link vpn:transmission -d dperson/nginx:aarch64 -w "http://transmission:9091/transmission;/transmission"

and it reports:

`
Generating a RSA private key

................................................................................................................+++++

.........................+++++

writing new private key to '/etc/nginx/ssl/privkey.pem'

-----

2020/03/28 10:53:16 [emerg] 6#6: the size 52428800 of shared memory zone "SSL" conflicts with already declared size 2097152 in /etc/nginx/conf.d/sessions.conf:2

nginx: [emerg] the size 52428800 of shared memory zone "SSL" conflicts with already declared size 2097152 in /etc/nginx/conf.d/sessions.conf:2

`

I tried to run 

docker run -it --name web -d dperson/nginx:aarch64

The error persists.

**Comment by dperson** [comment]
I have to apologize, Nginx doesn't actually build any Alpine packages except those for x86_64, so I'm not getting the correct package that the container knows how to deal with. I can't fix this with the time that I have to dedicate to the issue. Sorry.
