### ISSUE TITLE
multible basic auth users with env not possible

### ISSUE THREAD

**Issue by janstuemmel** [dperson/nginx#34]
Is there a possiblity to define multible users via environment variables? I found out that it's possible via command line args (`-U "foo;bar" -U "baz;bla"`). 

It would be pretty useful to assign it via `HTTPUSER` because it's not good to define passwords in a docker-compose file for example.

My suggestion would be to define them in `HTTPUSER` with a separator like `,`: `HTTPUSER=foo;bar,baz;bla`

https://github.com/dperson/nginx/blob/3d00052601d3771d8af9360f22c10eef84468d65/nginx.sh#L692

**Comment by dperson** [comment]
I added a way to do so now. Check the latest version. Every variable starting with `HTTPUSER` will be evaluated.
