### ISSUE TITLE
Getting plex to run with nginx

### ISSUE THREAD

**Issue by cd228** [dperson/nginx#35]
Hello. 

I have a setup where I run deluge through a container with nordvpn and access it through nginx using the following code:
sudo docker run -it --name web -p 80:80 -p 443:443 --link vpn:deluge \
            --link vpn:plex -d dperson/nginx \
            -w "http://deluge:8112/;/deluge;X-Deluge-Base \"/deluge/\"" \

I want to do the same with plex, but cannot access plex. I have tried with 
-w "http://plex:32400/;/plex"

as well as 
-w "http://plex:32400/web/;/plex"

but i cannot get it to work. Any suggestions?

**Comment by dperson** [comment]
I've found that a trailing `/` is normally needed for the proxies to function correctly, IE:
```
-w "http://plex:32400/;/plex/"
```

**Comment by cd228** [comment]
> 
> 
> I've found that a trailing `/` is normally needed for the proxies to function correctly, IE:
> 
> ```
> -w "http://plex:32400/;/plex/"
> ```

When I use the code above I get an error "This XML file does not appear to have any style information associated with it.".
When I use the path of plex: "http://plex:32400/web/;/plex/"
I get the error: 404 Not Found

**Comment by dperson** [comment]
Hmm, I don't run plex anymore. I never had it going through the reverse proxy, or using the VPN containers network stack. That being said, https://www.htpcguides.com/configure-plex-media-server-reverse-proxy-nginx-linux/ seems to say that plex only works if it's being accessed under the `/web/` URI. So give this a try:
```
-w "http://plex:32400/;/web/"
```

**Comment by cd228** [comment]
This code got me to the front page of plex
-w "http://plex:32400/web/;/web/"

However, it fails to set up the plex server. 

Without running through vpn and nginx, it works fine.

**Comment by dperson** [comment]
Hmm, since plex seems to be very particular about it's URI, why don't you try the `-W` instead of `-w`? It would be something like: `-w "http://plex:32400/;plex.<docker.server.name>"`

You'd also have to setup a DNS CNAME or just a host entry so that `<plex.docker.server.name>` resolves to the right IP. But it would see if it's just that it expects (has hardcoded URIs relative to `/`).
