### ISSUE TITLE
nginx proxy unreachable

### ISSUE THREAD

**Issue by kronnnnnn** [dperson/nginx#6]
Just stuck, feels like I'm doing everything right below but it's just failing to allow me to access transmission....  I'm running your openvpn-client and attempting to pass that traffic through the proxy from transmission.

`docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn-client -v /opt/openvpn-client:/vpn:ro --restart=always -d dperson/openvpn-client`

This seems good.  

> Thu Oct 27 14:32:07 2016 Initialization Sequence Completed

Then I start transmission and assign the net to the vpn-client container

`docker run -it --name transmission --net=container:vpn-client -d dperson/transmission`

Then for the proxy. Seems so straight forward with..

```
docker run -it --name vpn-proxy -p 80:80 -p 443:443 --link vpn-client:transmission \
            -d dperson/nginx -w "http://transmission:9091/transmission;/transmission"
```

transmission is up and when i nav to what I expect is the site I get this. so close..

http://imgur.com/a/Iy4gM

**Comment by dperson** [comment]
The screenshot you sent is of connecting directly to the transmission container on port `9091`. You're not using the nginx proxy at all. To do so, connect to the IP or DNS name of the system running docker on either port `80` or `443`.

I hope that I understood the question / issue correctly. Please let me know if you get any errors from nginx. Thanks.

**Comment by kronnnnnn** [comment]
Ok, I see what your saying here. When attempting to access either port for that docker machine I get the errors below.

192.168.1.107:80    ---->  403 Forbidden
192.168.1.107:443  ---->  400 Bad Request

Seems like I want to add -p 9091 to the run command and it should pull that port through for me, but it doesn't either.

But....  when access 192.168.1.107/transmission/ I get a 409: conflict.  hmm.

![image](https://cloud.githubusercontent.com/assets/5401067/19776811/3a402a64-9c3b-11e6-9133-d7635d7b7be9.png)

**Comment by dperson** [comment]
The connection to port `9091` doesn't work because once it's using the VPN clients network, it tries to route the return traffic over that link as well... because the docker containers run in a separate virtual network from your physical network. Making nginx a reverse web proxy (which is on the same local virtual network), gets around the routing issue.

I've never gotten the `409` HTTP response... can you supply the `docker logs <transmission_container>` and `docker logs <nginx_container>` output (replacing `<transmission_container>` and `<nginx_container>` with their real names)? It could provide us with a clue into what is going wrong. Thanks.

**Comment by kronnnnnn** [comment]
Sure, I'll start with the VPN which I know shouldn't be causing issues but whatever.

**docker logs vpn-client**

> Thu Oct 27 17:55:34 2016 OpenVPN 2.3.11 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on May 23 2016
> Thu Oct 27 17:55:34 2016 library versions: OpenSSL 1.0.2j  26 Sep 2016, LZO 2.08
> Thu Oct 27 17:55:34 2016 UDPv4 link local: [undef]
> Thu Oct 27 17:55:34 2016 UDPv4 link remote: [AF_INET]96.44.142.186:443
> Thu Oct 27 17:55:34 2016 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Thu Oct 27 17:55:34 2016 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1542', remote='link-mtu 1574'
> Thu Oct 27 17:55:34 2016 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1500', remote='tun-mtu 1532'
> Thu Oct 27 17:55:34 2016 [TG-OVPN-CA] Peer Connection Initiated with [AF_INET]96.44.142.186:443
> Thu Oct 27 17:55:37 2016 TUN/TAP device tun0 opened
> Thu Oct 27 17:55:37 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
> Thu Oct 27 17:55:37 2016 /sbin/ip link set dev tun0 up mtu 1500
> Thu Oct 27 17:55:37 2016 /sbin/ip addr add dev tun0 local 10.9.0.6 peer 10.9.0.5
> Thu Oct 27 17:55:37 2016 Initialization Sequence Completed

**docker logs transmission**

> [2016-10-27 17:58:12.793] Transmission 2.92 (14714) started (session.c:738)
> [2016-10-27 17:58:12.793] RPC Server Adding address to whitelist: \* (rpc-server.c:903)
> [2016-10-27 17:58:12.793] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1110)
> [2016-10-27 17:58:12.793] RPC Server Whitelist enabled (rpc-server.c:1114)
> [2016-10-27 17:58:12.793] RPC Server Password required (rpc-server.c:1117)
> [2016-10-27 17:58:12.793] Port Forwarding Stopped (port-forwarding.c:180)
> [2016-10-27 17:58:12.793] UDP Failed to set receive buffer: requested 4194304, got 425984 (tr-udp.c:84)
> [2016-10-27 17:58:12.793] UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (tr-udp.c:89)
> [2016-10-27 17:58:12.793] UDP Failed to set send buffer: requested 1048576, got 425984 (tr-udp.c:95)
> [2016-10-27 17:58:12.793] UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (tr-udp.c:100)
> [2016-10-27 17:58:12.793] DHT Generating new id (tr-dht.c:311)
> [2016-10-27 17:58:12.793] Using settings from "/var/lib/transmission-daemon/info" (daemon.c:528)
> [2016-10-27 17:58:12.793] Saved "/var/lib/transmission-daemon/info/settings.json" (variant.c:1266)
> [2016-10-27 17:58:12.793] transmission-daemon requiring authentication (daemon.c:554)
> [2016-10-27 17:58:34.793] DHT Attempting bootstrap from dht.transmissionbt.com (tr-dht.c:249)

**docker logs vpn-proxy**

> Generating a 2048 bit RSA private key
> ...........................................................................................................................+++
> .................................................+++
> 
> ## writing new private key to '/etc/nginx/ssl/privkey.pem'
> 
> 2016/10/27 18:04:44 [error] 31#31: *4 directory index of "/srv/www/" is forbidden, client: 192.168.1.84, server: localhost, request: "GET / HTTP/1.1", host: "192.168.1.107"
> 192.168.1.84 - - [27/Oct/2016:18:04:44 +0000] "GET / HTTP/1.1" 403 198 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36" "-" 0.000 -
> 192.168.1.84 - - [27/Oct/2016:18:05:04 +0000] "GET /transmission/ HTTP/1.1" 400 673 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36" "-" 0.000 -
> 192.168.1.84 - - [27/Oct/2016:18:05:04 +0000] "GET /favicon.ico HTTP/1.1" 400 673 "http://192.168.1.107:443/transmission/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36" "-" 0.000 -
> 2016/10/27 18:05:40 [error] 31#31: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.84, server: localhost, request: "GET /sickrage/ HTTP/1.1", upstream: "http://172.17.0.11:8081/sickrage/", host: "192.168.1.107"
> 192.168.1.84 - - [27/Oct/2016:18:05:40 +0000] "GET /sickrage/ HTTP/1.1" 502 537 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36" "-" 0.000 0.000

Tried to add another app in the proxy, not that is would help/hurt at this point.

```
docker run -it --name vpn-proxy -p 80:80 -p 443:443 \
--link vpn-client:transmission \
--link vpn-client:sickrage \
-d dperson/nginx \
-w "http://transmission:9091/transmission;/transmission" \
-w "http://sickrage:8081/sickrage;/sickrage"
```

**Comment by dperson** [comment]
Hmm, nothing really stands out. It all looks good, except of course the `400` errors while trying to connect to transmission and `502` errors for sickrage...

I doubt that adding sickrage would hurt, the only thing I can think of is if docker was unhappy having two different `--links` to the same container. If you didn't get any errors though, it should be fine.

**Comment by kronnnnnn** [comment]
Thanks for the help so far.  I'm going to try it on a VM later tonight and see. btw running Ubuntu Server 16.04 if that makes a difference.

**Comment by kronnnnnn** [comment]
Progress... I wiped all the containers and deleted all of the previous images (not that it should help). With all of the same container run's above I'm getting the page to display for both transmission and sickrage.  While sickrage displays a bare site where the css/style is missing. Clicking on any link removes the /sickrage/home and sends you to /home where the proxy fails.

![image](https://cloud.githubusercontent.com/assets/5401067/19806528/3787b566-9ce1-11e6-8860-e0592b7ec8d2.png)

Transmission only displays the 409 error but does request a username/password before.
![image](https://cloud.githubusercontent.com/assets/5401067/19806595/8f155158-9ce1-11e6-9866-b0cf9f1c80d1.png)

Proxy logs - http://pastebin.com/gvDSVstE
