### ISSUE TITLE
Feature request: Proxy multiple containers

### ISSUE THREAD

**Issue by jfjallid** [dperson/nginx#7]
I've used your combination of the openvpn-client, transmission and nginx containers and I'm wondering if it would be possible to use the nginx container to not only proxy traffic to the transmision container but also to other docker containers that need ssl termination. Is this something that works now or would be possible to implement?

**Comment by dperson** [comment]
I was on vacation, and just saw your question. Yes, it currently works to proxy as many containers as you'd like.
