### ISSUE TITLE
Add support for TCP proxying

### ISSUE THREAD

**Issue by daenney** [dperson/nginx#8]
Since nginx 1.9.0 (the open source one) support for TCP proxying has been added with the inclusion of the [Stream Core module](http://nginx.org/en/docs/stream/ngx_stream_core_module.html).

Would it be possible to add support for configuring TCP proxies? This would greatly help out with some of the "how to expose a non-HTTP service" issue people are having with dperson/openvpn-client 😄.

**Comment by dperson** [comment]
Okay, I just added a `-T` command line option to setup a stream proxy. I don't need, and am not using the change, but have pulled the latest build and can tell you at least that it didn't break anything else.

If you run into any problems with it please let me know (along with any error messages). Thanks.

**Comment by daenney** [comment]
That was quick, thanks!

**Comment by dperson** [comment]
I would have added it sooner, but missed that it was added to the open source version in the release notes. Thanks for the heads up.
