### ISSUE TITLE
Getting nginx to work with Deluge container

### ISSUE THREAD

**Issue by yuuzhan** [dperson/nginx#9]
I am not sure if I am doing something wrong, but I cannot seem to get this to work with Deluge

Here is how I setup the Deluge container (hooked into your great openvpn-client docker):
docker create --name deluge --net=container:vpn -e PUID=1000 -e PGID=1000 -e TZ=America/Toronto -v /docker/deluge/downloads:/downloads -v /docker/deluge/config:/config linuxserver/deluge

And the nginx link

sudo docker run -it --name web -p 80:80 -p 443:443 --link vpn:deluge -d dperson/nginx -w "http://deluge:8112/;/deluge"

Any help would be appriciated!

Thanks in advance.

**Comment by dperson** [comment]
First the basics (on the docker host run):

- Did either container exit (check the status column): `sudo docker ps -a`
- Can you connect to both:
  - `curl -Ls http://$(sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' deluge):8112/`
  - `curl -Ls http://$(sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' web)/`
- Do you have error messages:
  - `sudo docker logs deluge`
  - `sudo docker logs web`

**Comment by yuuzhan** [comment]
The basics!

1. The container did not exit
```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
3bd0a9eb8bf4        dperson/nginx            "nginx.sh -w http://d"   11 hours ago        Up 11 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   web
d9b2a91dded0        linuxserver/deluge       "/init"                  11 hours ago        Up 11 hours                                                    deluge
de4ac46918e5        dperson/openvpn-client   "openvpn.sh -f -r 192"   13 hours ago        Up 13 hours                                                    vpn
```
2. From the host

```
root@testBox:/home/jason# curl -Ls http://$(sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' deluge):8112/
root@testBox:/home/jason# curl -Ls http://$(sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' web)/
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.11.9</center>
</body>
</html>

```

3. See Attached.  I have done a few tries at it :)

[delugeLogs.txt](https://github.com/dperson/nginx/files/737677/delugeLogs.txt)
[webLogs.txt](https://github.com/dperson/nginx/files/737678/webLogs.txt)

**Comment by yuuzhan** [comment]
As a note, when using net=host, I can connect to the deluge web ui without any issues.  I can do some more testing.  I am running a VM with a snapshot so I can do lots of testing without any issues.  I can even export the VM (Virtualbox) and send you a link if you want.

**Comment by yuuzhan** [comment]
So, it seems the issue lies on the Deluge side, with the inability to set a basedir without apache installed.

That said, using this (hack) I was able to get full functionality:
`docker run -it --name web -p 80:80 -p 443:443 -e SSI=y --link vpn:deluge -d dperson/nginx -w "http://deluge:8112/;/deluge" -w "http://deluge:8112/css;/css" -w "http://deluge:8112/js;/js" -w "http://deluge:8112/themes;/themes" -w "http://deluge:8112/icons;/icons" -w "http://deluge:8112/gettext.js;/gettext.js" -w "http://deluge:8112/render;/render" -w "http://deluge:8112/images;/images"`

**Comment by dperson** [comment]
Glad you got it working, I meant to get back to you earlier. The no output when trying to curl from the Deluge container directly, pretty strongly indicated the issue was there.

**Comment by dperson** [comment]
FYI, I use transmission (a different BT client), and have a container for it [dperson/transmission](https://hub.docker.com/r/dperson/transmission/). I like it better, but YMMV.

**Comment by yuuzhan** [comment]
Indeed.  I used it for a while however its scheduling was not what I was looking for.  My ISP lets me have unlimited bandwidth between certain hours :)
